// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CqrsMessageType int32

const (
	CqrsMessageType_COMMAND CqrsMessageType = 0
	CqrsMessageType_EVENT   CqrsMessageType = 1
)

var CqrsMessageType_name = map[int32]string{
	0: "COMMAND",
	1: "EVENT",
}

var CqrsMessageType_value = map[string]int32{
	"COMMAND": 0,
	"EVENT":   1,
}

func (x CqrsMessageType) String() string {
	return proto.EnumName(CqrsMessageType_name, int32(x))
}

func (CqrsMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

type CqrsHeader struct {
	Type                 CqrsMessageType        `protobuf:"varint,1,opt,name=type,proto3,enum=main.CqrsMessageType" json:"type,omitempty"`
	Id                   string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CorrelationId        string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AggregateId          string                 `protobuf:"bytes,4,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateName        string                 `protobuf:"bytes,5,opt,name=aggregate_name,json=aggregateName,proto3" json:"aggregate_name,omitempty"`
	ProcessId            string                 `protobuf:"bytes,6,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ProcessName          string                 `protobuf:"bytes,7,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	SentDate             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sent_date,json=sentDate,proto3" json:"sent_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CqrsHeader) Reset()         { *m = CqrsHeader{} }
func (m *CqrsHeader) String() string { return proto.CompactTextString(m) }
func (*CqrsHeader) ProtoMessage()    {}
func (*CqrsHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *CqrsHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CqrsHeader.Unmarshal(m, b)
}
func (m *CqrsHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CqrsHeader.Marshal(b, m, deterministic)
}
func (m *CqrsHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CqrsHeader.Merge(m, src)
}
func (m *CqrsHeader) XXX_Size() int {
	return xxx_messageInfo_CqrsHeader.Size(m)
}
func (m *CqrsHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_CqrsHeader.DiscardUnknown(m)
}

var xxx_messageInfo_CqrsHeader proto.InternalMessageInfo

func (m *CqrsHeader) GetType() CqrsMessageType {
	if m != nil {
		return m.Type
	}
	return CqrsMessageType_COMMAND
}

func (m *CqrsHeader) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CqrsHeader) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *CqrsHeader) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *CqrsHeader) GetAggregateName() string {
	if m != nil {
		return m.AggregateName
	}
	return ""
}

func (m *CqrsHeader) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

func (m *CqrsHeader) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *CqrsHeader) GetSentDate() *timestamppb.Timestamp {
	if m != nil {
		return m.SentDate
	}
	return nil
}

type BookRoom struct {
	Header               *CqrsHeader            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RoomId               string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	GuestName            string                 `protobuf:"bytes,3,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	StartDate            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BookRoom) Reset()         { *m = BookRoom{} }
func (m *BookRoom) String() string { return proto.CompactTextString(m) }
func (*BookRoom) ProtoMessage()    {}
func (*BookRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1}
}

func (m *BookRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRoom.Unmarshal(m, b)
}
func (m *BookRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRoom.Marshal(b, m, deterministic)
}
func (m *BookRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRoom.Merge(m, src)
}
func (m *BookRoom) XXX_Size() int {
	return xxx_messageInfo_BookRoom.Size(m)
}
func (m *BookRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRoom.DiscardUnknown(m)
}

var xxx_messageInfo_BookRoom proto.InternalMessageInfo

func (m *BookRoom) GetHeader() *CqrsHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BookRoom) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *BookRoom) GetGuestName() string {
	if m != nil {
		return m.GuestName
	}
	return ""
}

func (m *BookRoom) GetStartDate() *timestamppb.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *BookRoom) GetEndDate() *timestamppb.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

type RoomBooked struct {
	Header               *CqrsHeader            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ReservationId        string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	RoomId               string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	GuestName            string                 `protobuf:"bytes,4,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	Price                int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	StartDate            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoomBooked) Reset()         { *m = RoomBooked{} }
func (m *RoomBooked) String() string { return proto.CompactTextString(m) }
func (*RoomBooked) ProtoMessage()    {}
func (*RoomBooked) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{2}
}

func (m *RoomBooked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomBooked.Unmarshal(m, b)
}
func (m *RoomBooked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomBooked.Marshal(b, m, deterministic)
}
func (m *RoomBooked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomBooked.Merge(m, src)
}
func (m *RoomBooked) XXX_Size() int {
	return xxx_messageInfo_RoomBooked.Size(m)
}
func (m *RoomBooked) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomBooked.DiscardUnknown(m)
}

var xxx_messageInfo_RoomBooked proto.InternalMessageInfo

func (m *RoomBooked) GetHeader() *CqrsHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RoomBooked) GetReservationId() string {
	if m != nil {
		return m.ReservationId
	}
	return ""
}

func (m *RoomBooked) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomBooked) GetGuestName() string {
	if m != nil {
		return m.GuestName
	}
	return ""
}

func (m *RoomBooked) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *RoomBooked) GetStartDate() *timestamppb.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *RoomBooked) GetEndDate() *timestamppb.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

type OrderBeer struct {
	Header               *CqrsHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ReservationId        string      `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	RoomId               string      `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Count                int64       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OrderBeer) Reset()         { *m = OrderBeer{} }
func (m *OrderBeer) String() string { return proto.CompactTextString(m) }
func (*OrderBeer) ProtoMessage()    {}
func (*OrderBeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{3}
}

func (m *OrderBeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBeer.Unmarshal(m, b)
}
func (m *OrderBeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBeer.Marshal(b, m, deterministic)
}
func (m *OrderBeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBeer.Merge(m, src)
}
func (m *OrderBeer) XXX_Size() int {
	return xxx_messageInfo_OrderBeer.Size(m)
}
func (m *OrderBeer) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBeer.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBeer proto.InternalMessageInfo

func (m *OrderBeer) GetHeader() *CqrsHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *OrderBeer) GetReservationId() string {
	if m != nil {
		return m.ReservationId
	}
	return ""
}

func (m *OrderBeer) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *OrderBeer) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type BeerOrdered struct {
	Header               *CqrsHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ReservationId        string      `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	RoomId               string      `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Count                int64       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BeerOrdered) Reset()         { *m = BeerOrdered{} }
func (m *BeerOrdered) String() string { return proto.CompactTextString(m) }
func (*BeerOrdered) ProtoMessage()    {}
func (*BeerOrdered) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{4}
}

func (m *BeerOrdered) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeerOrdered.Unmarshal(m, b)
}
func (m *BeerOrdered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeerOrdered.Marshal(b, m, deterministic)
}
func (m *BeerOrdered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeerOrdered.Merge(m, src)
}
func (m *BeerOrdered) XXX_Size() int {
	return xxx_messageInfo_BeerOrdered.Size(m)
}
func (m *BeerOrdered) XXX_DiscardUnknown() {
	xxx_messageInfo_BeerOrdered.DiscardUnknown(m)
}

var xxx_messageInfo_BeerOrdered proto.InternalMessageInfo

func (m *BeerOrdered) GetHeader() *CqrsHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BeerOrdered) GetReservationId() string {
	if m != nil {
		return m.ReservationId
	}
	return ""
}

func (m *BeerOrdered) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *BeerOrdered) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("main.CqrsMessageType", CqrsMessageType_name, CqrsMessageType_value)
	proto.RegisterType((*CqrsHeader)(nil), "main.CqrsHeader")
	proto.RegisterType((*BookRoom)(nil), "main.BookRoom")
	proto.RegisterType((*RoomBooked)(nil), "main.RoomBooked")
	proto.RegisterType((*OrderBeer)(nil), "main.OrderBeer")
	proto.RegisterType((*BeerOrdered)(nil), "main.BeerOrdered")
}

func init() {
	proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9)
}

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x6a, 0x13, 0x4d,
	0x18, 0xc6, 0xbf, 0xcd, 0xff, 0x7d, 0xb7, 0xcd, 0x17, 0x86, 0x8a, 0x4b, 0x41, 0x8c, 0x91, 0x40,
	0xea, 0xc1, 0x2e, 0x44, 0x44, 0x3c, 0x34, 0x6d, 0xc1, 0x1c, 0x24, 0x85, 0x25, 0x78, 0xe0, 0x49,
	0x98, 0xec, 0xbc, 0x6e, 0x87, 0x74, 0x77, 0xd6, 0x99, 0x49, 0xa0, 0xde, 0x82, 0x78, 0x09, 0x5e,
	0x85, 0xf7, 0xe3, 0xb5, 0xc8, 0xcc, 0x24, 0x69, 0x08, 0x62, 0xd5, 0x83, 0x1e, 0xce, 0xf3, 0x3e,
	0xfb, 0xce, 0xf3, 0xfc, 0x26, 0x04, 0x8e, 0x70, 0x8d, 0x85, 0x56, 0x51, 0x29, 0x85, 0x16, 0xa4,
	0x96, 0x53, 0x5e, 0x9c, 0x3e, 0xcd, 0x84, 0xc8, 0x6e, 0x30, 0xb6, 0xda, 0x62, 0xf5, 0x31, 0xd6,
	0x3c, 0x47, 0xa5, 0x69, 0x5e, 0x3a, 0x5b, 0xef, 0x7b, 0x05, 0xe0, 0xfc, 0x93, 0x54, 0xef, 0x90,
	0x32, 0x94, 0xe4, 0x0c, 0x6a, 0xfa, 0xb6, 0xc4, 0xd0, 0xeb, 0x7a, 0x83, 0xf6, 0xf0, 0x51, 0x64,
	0x96, 0x44, 0x66, 0x3e, 0x41, 0xa5, 0x68, 0x86, 0xb3, 0xdb, 0x12, 0x13, 0x6b, 0x21, 0x6d, 0xa8,
	0x70, 0x16, 0x56, 0xba, 0xde, 0xc0, 0x4f, 0x2a, 0x9c, 0x91, 0x3e, 0xb4, 0x53, 0x21, 0x25, 0xde,
	0x50, 0xcd, 0x45, 0x31, 0xe7, 0x2c, 0xac, 0xda, 0xd9, 0xf1, 0x9e, 0x3a, 0x66, 0xe4, 0x19, 0x1c,
	0xd1, 0x2c, 0x93, 0x98, 0x51, 0x8d, 0xc6, 0x54, 0xb3, 0xa6, 0x60, 0xa7, 0x8d, 0xed, 0xa6, 0x3b,
	0x4b, 0x41, 0x73, 0x0c, 0xeb, 0x6e, 0xd3, 0x4e, 0x9d, 0xd2, 0x1c, 0xc9, 0x13, 0x80, 0x52, 0x8a,
	0x14, 0x95, 0x32, 0x7b, 0x1a, 0xd6, 0xe2, 0x6f, 0x14, 0x77, 0xd1, 0x76, 0x6c, 0x77, 0x34, 0xdd,
	0x45, 0x1b, 0xcd, 0x6e, 0x78, 0x0d, 0xbe, 0xc2, 0x42, 0xcf, 0x19, 0xd5, 0x18, 0xb6, 0xba, 0xde,
	0x20, 0x18, 0x9e, 0x46, 0x8e, 0x58, 0xb4, 0x25, 0x16, 0xcd, 0xb6, 0xc4, 0x92, 0x96, 0x31, 0x5f,
	0x50, 0x8d, 0xbd, 0x1f, 0x1e, 0xb4, 0x46, 0x42, 0x2c, 0x13, 0x21, 0x72, 0x32, 0x80, 0xc6, 0xb5,
	0xa5, 0x67, 0xa9, 0x05, 0xc3, 0xce, 0x1d, 0x35, 0x47, 0x35, 0xd9, 0xcc, 0xc9, 0x63, 0x68, 0x4a,
	0x21, 0xf2, 0xf9, 0x8e, 0x5b, 0xc3, 0x1c, 0xc7, 0xcc, 0x54, 0xc9, 0x56, 0xa8, 0xb4, 0x4b, 0xea,
	0xb8, 0xf9, 0x56, 0xb1, 0x39, 0xdf, 0x00, 0x28, 0x4d, 0xe5, 0x26, 0x68, 0xed, 0xde, 0xa0, 0xbe,
	0x75, 0x9b, 0xa4, 0xe4, 0x15, 0xb4, 0xb0, 0x60, 0xee, 0xc3, 0xfa, 0xbd, 0x1f, 0x36, 0xb1, 0x60,
	0xb6, 0xe0, 0xb7, 0x0a, 0x80, 0x29, 0x67, 0x4a, 0x22, 0xfb, 0x8b, 0x8a, 0x7d, 0x68, 0x4b, 0x54,
	0x28, 0xd7, 0xbb, 0x5f, 0x81, 0x6b, 0x7a, 0xbc, 0xa7, 0x8e, 0xd9, 0x3e, 0x89, 0xea, 0x6f, 0x48,
	0xd4, 0x0e, 0x49, 0x9c, 0x40, 0xbd, 0x94, 0x3c, 0x75, 0x5d, 0xaa, 0x89, 0x3b, 0x1c, 0xf0, 0x69,
	0xfc, 0x2b, 0x9f, 0xe6, 0x9f, 0xf3, 0xf9, 0xe2, 0x81, 0x7f, 0x25, 0x19, 0xca, 0x11, 0xa2, 0x7c,
	0x40, 0x3c, 0x27, 0x50, 0x4f, 0xc5, 0xaa, 0xd0, 0x96, 0x4c, 0x35, 0x71, 0x87, 0xde, 0x57, 0x0f,
	0x02, 0x13, 0xc4, 0x26, 0x7a, 0xd0, 0xe7, 0xfa, 0x65, 0x9e, 0x17, 0x67, 0xf0, 0xff, 0xc1, 0x7f,
	0x06, 0x09, 0xa0, 0x79, 0x7e, 0x35, 0x99, 0xbc, 0x9d, 0x5e, 0x74, 0xfe, 0x23, 0x3e, 0xd4, 0x2f,
	0xdf, 0x5f, 0x4e, 0x67, 0x1d, 0x6f, 0xd4, 0xff, 0xf0, 0x3c, 0xe3, 0xfa, 0x7a, 0xb5, 0x88, 0x52,
	0x91, 0xc7, 0x92, 0x2e, 0x69, 0x2e, 0xd6, 0xfc, 0x73, 0xbc, 0xe4, 0x45, 0xca, 0x25, 0xe5, 0x32,
	0x36, 0xd1, 0x17, 0x0d, 0xfb, 0x18, 0x2f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xd6, 0x99,
	0x20, 0xe4, 0x04, 0x00, 0x00,
}
