// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookRoom struct {
	RoomId               string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	GuestName            string                 `protobuf:"bytes,2,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	StartDate            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BookRoom) Reset()         { *m = BookRoom{} }
func (m *BookRoom) String() string { return proto.CompactTextString(m) }
func (*BookRoom) ProtoMessage()    {}
func (*BookRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *BookRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRoom.Unmarshal(m, b)
}
func (m *BookRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRoom.Marshal(b, m, deterministic)
}
func (m *BookRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRoom.Merge(m, src)
}
func (m *BookRoom) XXX_Size() int {
	return xxx_messageInfo_BookRoom.Size(m)
}
func (m *BookRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRoom.DiscardUnknown(m)
}

var xxx_messageInfo_BookRoom proto.InternalMessageInfo

func (m *BookRoom) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *BookRoom) GetGuestName() string {
	if m != nil {
		return m.GuestName
	}
	return ""
}

func (m *BookRoom) GetStartDate() *timestamppb.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *BookRoom) GetEndDate() *timestamppb.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

type RoomBooked struct {
	ReservationId        string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	RoomId               string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	GuestName            string                 `protobuf:"bytes,3,opt,name=guest_name,json=guestName,proto3" json:"guest_name,omitempty"`
	Price                int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	StartDate            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoomBooked) Reset()         { *m = RoomBooked{} }
func (m *RoomBooked) String() string { return proto.CompactTextString(m) }
func (*RoomBooked) ProtoMessage()    {}
func (*RoomBooked) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1}
}

func (m *RoomBooked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomBooked.Unmarshal(m, b)
}
func (m *RoomBooked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomBooked.Marshal(b, m, deterministic)
}
func (m *RoomBooked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomBooked.Merge(m, src)
}
func (m *RoomBooked) XXX_Size() int {
	return xxx_messageInfo_RoomBooked.Size(m)
}
func (m *RoomBooked) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomBooked.DiscardUnknown(m)
}

var xxx_messageInfo_RoomBooked proto.InternalMessageInfo

func (m *RoomBooked) GetReservationId() string {
	if m != nil {
		return m.ReservationId
	}
	return ""
}

func (m *RoomBooked) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomBooked) GetGuestName() string {
	if m != nil {
		return m.GuestName
	}
	return ""
}

func (m *RoomBooked) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *RoomBooked) GetStartDate() *timestamppb.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *RoomBooked) GetEndDate() *timestamppb.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

type OrderBeer struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBeer) Reset()         { *m = OrderBeer{} }
func (m *OrderBeer) String() string { return proto.CompactTextString(m) }
func (*OrderBeer) ProtoMessage()    {}
func (*OrderBeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{2}
}

func (m *OrderBeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBeer.Unmarshal(m, b)
}
func (m *OrderBeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBeer.Marshal(b, m, deterministic)
}
func (m *OrderBeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBeer.Merge(m, src)
}
func (m *OrderBeer) XXX_Size() int {
	return xxx_messageInfo_OrderBeer.Size(m)
}
func (m *OrderBeer) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBeer.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBeer proto.InternalMessageInfo

func (m *OrderBeer) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *OrderBeer) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type BeerOrdered struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeerOrdered) Reset()         { *m = BeerOrdered{} }
func (m *BeerOrdered) String() string { return proto.CompactTextString(m) }
func (*BeerOrdered) ProtoMessage()    {}
func (*BeerOrdered) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{3}
}

func (m *BeerOrdered) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeerOrdered.Unmarshal(m, b)
}
func (m *BeerOrdered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeerOrdered.Marshal(b, m, deterministic)
}
func (m *BeerOrdered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeerOrdered.Merge(m, src)
}
func (m *BeerOrdered) XXX_Size() int {
	return xxx_messageInfo_BeerOrdered.Size(m)
}
func (m *BeerOrdered) XXX_DiscardUnknown() {
	xxx_messageInfo_BeerOrdered.DiscardUnknown(m)
}

var xxx_messageInfo_BeerOrdered proto.InternalMessageInfo

func (m *BeerOrdered) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *BeerOrdered) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*BookRoom)(nil), "main.BookRoom")
	proto.RegisterType((*RoomBooked)(nil), "main.RoomBooked")
	proto.RegisterType((*OrderBeer)(nil), "main.OrderBeer")
	proto.RegisterType((*BeerOrdered)(nil), "main.BeerOrdered")
}

func init() {
	proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9)
}

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0xdb, 0xb4, 0xcd, 0x54, 0x3d, 0x84, 0x82, 0xa5, 0x20, 0x96, 0x4a, 0xa1, 0xa7,
	0x04, 0x14, 0x0f, 0x8a, 0xa7, 0xe2, 0xa5, 0x17, 0x85, 0xe0, 0xc9, 0x4b, 0xd9, 0x66, 0xc7, 0xb8,
	0xd4, 0xdd, 0x29, 0x9b, 0x49, 0x0f, 0x3e, 0x97, 0x6f, 0xe6, 0x0b, 0x48, 0x76, 0x29, 0x96, 0x82,
	0x7f, 0x8f, 0x33, 0x99, 0x1f, 0xdf, 0xf7, 0x23, 0x0b, 0x07, 0xb8, 0x41, 0xc3, 0x65, 0xb2, 0xb6,
	0xc4, 0x14, 0xb7, 0xb4, 0x50, 0x66, 0x78, 0x5a, 0x10, 0x15, 0x2f, 0x98, 0xba, 0xdd, 0xb2, 0x7a,
	0x4a, 0x59, 0x69, 0x2c, 0x59, 0xe8, 0xb5, 0x3f, 0x1b, 0xbf, 0x05, 0xd0, 0x9d, 0x11, 0xad, 0x32,
	0x22, 0x1d, 0x1f, 0x43, 0xc7, 0x12, 0xe9, 0x85, 0x92, 0x83, 0x60, 0x14, 0x4c, 0xa3, 0xac, 0x5d,
	0x8f, 0x73, 0x19, 0x9f, 0x00, 0x14, 0x15, 0x96, 0xbc, 0x30, 0x42, 0xe3, 0xa0, 0xe1, 0xbe, 0x45,
	0x6e, 0x73, 0x27, 0x34, 0xc6, 0x57, 0x00, 0x25, 0x0b, 0xcb, 0x0b, 0x29, 0x18, 0x07, 0xad, 0x51,
	0x30, 0xed, 0x9d, 0x0f, 0x13, 0x1f, 0x9d, 0x6c, 0xa3, 0x93, 0x87, 0x6d, 0x74, 0x16, 0xb9, 0xeb,
	0x5b, 0xc1, 0x18, 0x5f, 0x42, 0x17, 0x8d, 0xf4, 0x60, 0xf8, 0x23, 0xd8, 0x41, 0x23, 0x6b, 0x6c,
	0xfc, 0x1e, 0x00, 0xd4, 0x95, 0xeb, 0xea, 0x28, 0xe3, 0x09, 0x1c, 0x59, 0x2c, 0xd1, 0x6e, 0x04,
	0x2b, 0x32, 0x9f, 0xfd, 0x0f, 0x77, 0xb6, 0x73, 0xb9, 0xeb, 0xd7, 0xf8, 0xc6, 0xaf, 0xb9, 0xef,
	0xd7, 0x87, 0x70, 0x6d, 0x55, 0xee, 0xd5, 0x9a, 0x99, 0x1f, 0xf6, 0xac, 0xc3, 0xff, 0x5a, 0xb7,
	0x7f, 0x6f, 0x7d, 0x0d, 0xd1, 0xbd, 0x95, 0x68, 0x67, 0x88, 0xf6, 0xeb, 0x9f, 0xd5, 0x87, 0x30,
	0xa7, 0xca, 0xb0, 0x73, 0x6c, 0x66, 0x7e, 0x18, 0xdf, 0x40, 0xaf, 0xc6, 0x1c, 0x8f, 0xf2, 0x8f,
	0xf4, 0x6c, 0xf2, 0x78, 0x56, 0x28, 0x7e, 0xae, 0x96, 0x49, 0x4e, 0x3a, 0xb5, 0x62, 0x25, 0x34,
	0x6d, 0xd4, 0x6b, 0xba, 0x52, 0x26, 0x57, 0x56, 0x28, 0x9b, 0xd6, 0xcf, 0x6d, 0xd9, 0x76, 0xed,
	0x2f, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x16, 0x72, 0x99, 0x8b, 0x02, 0x00, 0x00,
}
